### ISSUE TITLE
Add Footer 

### ISSUE THREAD

**Issue by bandya2003** [Atharva-cyber-dark/Portfolio-website-#2]
I can add footer for your website

**Comment by Samarthku** [comment]
Hello please assign me this issue

**Comment by itsekta** [comment]
Hi @Atharva-cyber-dark can you assign this to me?

**Comment by bandya2003** [comment]
@itsekta are you working on it?

**Comment by itsekta** [comment]
yeah, i'm working on it

**Comment by bandya2003** [comment]
> yeah, i'm working on it

Ohh great 👍🤝

**Comment by itsekta** [comment]
@bandya2003 in which file should i add the footer, there are so many files and there is one folder named with footer as well?

**Comment by bandya2003** [comment]
> @bandya2003 in which file should i add the footer, there are so many files and there is one folder named with footer as well?

Yup add it in the Footer Folder with the file having your name

**Comment by bandya2003** [comment]
@itsekta If you want to contribute to more repos do Checkout mine Ml training Repo  has an active Issue would be really helpful if you would work on it too

**Comment by itsekta** [comment]
> > @bandya2003 in which file should i add the footer, there are so many files and there is one folder named with footer as well?
> 
> Yup add it in the Footer Folder with the file having your name

ok

**Comment by itsekta** [comment]
> @itsekta If you want to contribute to more repos do Checkout mine Ml training Repo has an active Issue would be really helpful if you would work on it too

sure, I'll look into it

**Comment by bandya2003** [comment]
> > @itsekta If you want to contribute to more repos do Checkout mine Ml training Repo has an active Issue would be really helpful if you would work on it too
> 
> sure, I'll look into it

Yup thanks a lot

**Comment by itsekta** [comment]
Hi @bandya2003, this pull request (https://github.com/Atharva-cyber-dark/Portfolio-website-/pull/23) will close the footer issue please review it asap

**Comment by bandya2003** [comment]
> Hi @bandya2003, this pull request (https://github.com/Atharva-cyber-dark/Portfolio-website-/pull/23) will close the footer issue please review it asap

Just a sec

**Comment by bandya2003** [comment]
> Hi @bandya2003, this pull request (https://github.com/Atharva-cyber-dark/Portfolio-website-/pull/23) will close the footer issue please review it asap

Closing the issue🙌 thanks a lot

**Comment by itsekta** [comment]
@bandya2003 can you please add the hacktober-accepted label for the pull request

**Comment by bandya2003** [comment]
> @bandya2003 can you please add the hacktober-accepted label for the pull request

@Atharva-cyber-dark please have a look at it
